# Introduction {#introduction}

## What is Research Data Management?

Research data management comprises all parts of the "life cycle" of data.

It "is part of the research process, and aims to make the research process as
efficient as possible, and meet expectations and requirements of the university,
research funders, and legislation."
(https://www2.le.ac.uk/services/research-data/rdm/what-is-rdm)

## Why is Research Data Management important? 

According to [Labfolder.com (2018)](https://www.labfolder.com/research-data-management/)
research data management (RDM) is important as it:

- Saves time for research,

- Avoids risk of data loss,

- Ensures transparency and reproducibility,

- Increases data visibility and number of citations,

- Fulfills funders’ requirements and receives more grants,

- Produces new knowledge and makes more discoveries just by re-using data,

- Archives, retrieves and re-uses own data.

## Why RDM for small institutes? 

This document focuses on research data management at [small
institues](glossary.html#small-institute). In terms of data management, we found
the following characteristics of small institutes:

The transfer of knowledge is particularly important because the loss of 
knowledge can be considerable in case that an employee leaves the institute.

Small institutes do not have an IT department. They do not have employees that
are dedicated to data managment tasks only. Often, there are no data management
guidelines defined. Data management is not centrally organised but is left to
the different project leaders and researchers. All employees are expected to be
their own data experts. Depending on the individual skills of the different
employees, different levels of data handling practices are applied.

In small institutes, work is organised in terms of projects. There may not be an
overall strategy or target that is followed by the institute. Targets are
depending on research programmes and requirements may be set by funding
organisations. The projects may be very different in terms of amount and
diversity of data.

Small institutes have a simple organisational structure. This may allow for a 
simple informal exchange of information. This can lead to fast answers and 
decisions but very often has the drawback that processes are not documented 
sufficiently. In small institutes with a flat hierarchy innovations such as the
usage of new methods or tools very often start as initiatives of single 
employees or are first applied in single projects. Practices that have been 
proven to be beneficial may then be used in future projects or even be set as
a standard for the whole institute (bottom-up). It is less probable that 
the head of the institute sets guidelines to be followed consistently in all 
projects (top-down).

The aim of this document is to define best research data managment practices
that are assumed to be particular useful for small institutes.

<!-- Unterziele: z.B. Entwicklung eines internen Standards für Metadaten -->
<!-- Info on the document – create links between projects and thematic groups -->

## Recommended literature

A very good book on how research data management (RDM) improves reproducibility 
is provided by `r citet(manual["Kitzesetal_2018"])` and available online at: 
[http://practicereproducibleresearch.org/](http://practicereproducibleresearch.org/).

- [Introduction to research data management in the geosciences](http://doi.org/10.2312/lis.14.01) 
(in German!)
  
- [Handbook research data management](http://www.forschungsdatenmanagement.de/)
(in German!) `r citep(manual["Buettner_2011"])`
