## Data Storage

This chapter describes 

* where to store data files, see [Where to Store Data](#data-storage-where),
* what names to choose for files and folders, see 
[Naming of Files and Folders](#data-storage-naming),
* how to group files in folders, see [Folder Structures](#folder-structures).

With the following recommendations we intend to comply with the 
[Ten Simple Rules for Digital Data Storage](#storage-ten-simple-rules).

### Where to Store Data {#data-storage-where}

We want to store project relevant files on a KWB network drive that is 
accessible to all the persons working in the project.

We want to avoid that project relevant files are stored 

* locally on the hard drive of an employee or trainee or

* on the personal network drive assigned to an employee or trainee.

### Naming of Files and Folders {#data-storage-naming}

<!-- >We name and name and name. Because we do so much of it, we'd better do it well. -->
<!-- > -->
<!-- > --- `r citep(manual["martin2009"])` -->

In this section we define rules for good names for files and folders. We want to
apply these rules whenever we have the freedom to define our own names, i.e. 
when creating a new file or a new folder.

<!-- By giving rules for the naming of files and folders  -->
We pursue different objectives:

* *Objective 1:* Names should not cause problems during automated data 
processing. 

* *Objective 2:* Names should be meaningful to you and your colleagues. You and 
they should be able to guess what a folder or file contains so that required 
files are found easily. 

* *Objective 3:* Names should not cause problems when copying files within your 
(computer) system or between different systems, especially between different 
operating systems or systems in different countries.

We process files automatically. Listing or reading files with non-standard 
characters in their names often cause problems. These problems are easy to avoid
by sticking to some simple restrictive rules when naming files and folders.

#### Allowed Characters {-}

In order to meet *Objectives 1 and 3* we define the following 
**set of characters** that are allowed in file or folder names:

* upper case letters `A-Z`, 
* lower case letters `a-z`, 
* numbers `0-9`,
* underscore `_`,
* hyphen `-`,
* dot `.`.

See the FAQ chapter for answers to the following questions:

* [Why are special characters not allowed?](#faq-why-no-german-specials)
* [Why is the space character not allowed?](#faq-why-no-space)

Instead of German special characters (`ä`, `ö`, `ü`, `Ä`, `Ö`, `Ü`, `ß`) use the 
following substitutions: `ae`, `oe`, `ue`, `Ae`, `Oe`, `Ue`, `ss`.

Instead of space, use underscore `_` or hyphen `-` (see next).

#### Separation of Words or Parts of Words {-}

Use underscore to separate different words in the file or folder name that 
contain different types of information:

* `results_today`, `results_tomorrow` instead of `results-today`, 
`results-tomorrow`,

* `protocol_hauke`, `protocol_michael` instead of `protocol-hauke`, 
`protocol-michael`

Use hyphen `-` instead of underscore `_` to visually separate the parts of 
compound words or names:
  
* `site-1` instead of `site_1`, 

* `dissolved-oxygen` instead of `dissolved_oxygen`,

* `clean-data` instead of `clean_data`.

Use hyphen (or no separation at all) in dates (see below).

Using hyphen instead of underscore in composed words will not split the composed 
words into their parts when splitting a file or folder name at underscore.

For example, splitting the name 
`project-report_example-project-1_v1.0_2018-07-02` at underscore results in the 
following words (giving different types of information on the file or folder)

* `project-report` (type of document),

* `example-project-1` (name of related project),

* `v1.0` (version number),

* `2018-07-02` (version date).

#### Capitalisation {-}

```{block2 type = "rmdnote"}
Should we decide on if and when to use capitals, i.e. should we allow only one
of the following spellings: 
  
`dissolved-oxygen` (all lower case), 
`dissolved-Oxygen` (attributes lower case, nouns upper case), 
`Dissolved-oxygen` (first letter upper case),
`Dissolved-Oxygen` (all parts of compund words upper case)?
```

#### Formatting of Dates and Numbers {-}

We want to write **dates** in file or folder names in one of these forms:

* `yyyy-mm-dd` (e.g. `2018-06-28`)

* `yyyymmdd` (e.g. `20180628`)

By doing so, file names only differing in the date will display chronologically 
in file listings. This is because, by default, files are sorted alphanumerically
by their name. Using the first form improves the visual distinction of the year, 
month and day part of the date. Using hyphen instead of underscore will keep 
these parts together when splitting the name at underscore (see above). 

When using numbers in file or folder names to bring them into a certain order
we should use leading zeroes and specify the amount of digits that will be used,
e.g. `01`, `02`, `03` or `001`, `002`, `003`, etc.

#### Allowed Words {-}

In order to meet *Objective 2*, we should define **sets of allowed words** in
so called vocabularies. Only words from the vocabularies are then expected to
appear as words in file or folder names. Getting accustomed to the words from 
the vocabularies and their meanings allows for more precise file searching.

This is most important to clearly indicate that a file or folder relates to
"special objects", such as projects or organisations or monitoring sites. 
At least for projects and organisations we want to define vocabularies in which
"official" acronyms are defined for all projects and all organisations from 
which we expect to receive data (see the chapter on [acronyms](#acronyms)).
Always using the acronyms defined in the vocabularies allows to search for files 
or folders belonging to one specific project or being provided by one specific
organisation.

We could also define vocabularies of words describing other properties of a file
or folder. We could e.g. decide to always use `clean-data` instead of
`data-clean`, `cleaned-data`, `data-cleaning`, `Datenbereinigung`,
`bereinigte-daten`, etc.

#### Order of Words {-}

We could go one step further and define the order in which we expect the words 
to appear in a file or folder name. Which types of information should go first 
in the filename? The order of words determines in which way files are grouped
visually when being listed by their name. If the acronym of the organisation 
goes first, files are grouped by organisation. If the acronym of the monitoring
site goes first, files are grouped by monitoring site.

#### Allowed Languages {-}

Do not mix words from different languages within one and the same file or folder 
name. For example, use `regen-ereignis` or `rain-event` instead of `regen-event` 
or `rain-ereignis`.

Within one project, use either only English words or only German words in
file or folder names. This restriction may be too strict. However, I think that
we should follow this rule at least for the top level 
[folder structures](#folder-structures). It is not nice that we see folders
`AUFTRAEGE` (German) and `GROUNDWATER` (English) as folder names within the
same parent folder.

#### Avoid Very Long Names {-}

In order to meet *Objective 3*, very long file and folder names should be 
avoided. File and folder names should be 

* as long as necessary to be meaningful but at the same time 

* as short as possible. 

```{block2 type = "rmdwarning"}
In the Windows operating system, long file paths can cause problems when copying
files. If the full path to the target location of a file exceeds a certain 
length (between 255 and 260 characters) you get the following error message 
(here in German): `Die Dateinamen wären zu lang für den Zielordner. Kürzen Sie 
die Dateinamen und wiederholen Sie den Vorgang, oder verwenden Sie einen anderen 
Ort, der einen kürzeren Pfad hat.`
```

This problem can be avoided by 

* avoiding very long file or folder names,
* avoiding very deep [folder structures](#folder-structures).

If folder or file names are generated by software (e.g. logger software, 
modelling software, reference manager) we should check if the software allows to
modify the naming scheme. 

If we nevertheless have to deal with deeply nested folder structures and/or very 
long file or folder names we should store them in a flat folder hierarchy (i.e. 
not in `\\server\projekte$\department-name\projects\project-name\data-work-packages\work-package-one-meaning-the-following\modelling\scenario-one-meaning-the-following\results`).

#### Examples {-}

Examples for good file names:

* `AHRC_TechnicalApp_Response_20120925.docx` or
* `AHRC-TechnicalApp-Response20120925.docx`

Example for bad file names:

* `what we got back from funders about the data stuff.docx`

### Metadata (should go one level up!){#metadata}

Metadata are data about data. It is up to us to define 

* [what metadata](#metadata-what) (about [raw data](#raw-data), processed data,
produced plots, documents, reports, etc.) we want to store, 
<!-- Mindestanforderungen definieren (unterschieden nach Roh- und verarbeiteten -->
<!-- Daten) -->
  
* [where](#metadata-where) to store metadata and 

* [in what format](#metadata-format) to store metadata.

We plan to specify the requirements in more detail when dealing with the test
projects ([case studies](#case-studies)). Then, will also check 
[metadata standards](#metadata-standards).

Metadata about [raw data](#raw-data) should always be stored.

Metadata about processed data are also important. However, in case of automated
processing with a script, it may be possible to deduce the content of a 
generated file from the content of the script. 

#### Why Metadata? {#metadata-why}

Why should we store metadata about data? Metadata are required to 

* interpret [raw data](#raw-data), e.g. "Why are the oxygen values so high? 
Ah, I see, someone was there to clean the sensor!",

* gain an overview about available data,

* know what we are allowed to do with the data.

#### What Metadata to Store? {#metadata-what}

##### General

What information would someone need to find/re-use your data? E.g.

* Location, 

* Title, 

* Creator name, 

* Description, 

* Date collected?

##### Metadata about Raw Data

What are the most important information about [raw data](#raw-data) that we receive?

* Obtained from whom, when, via whom and which medium, e.g. 

    + `E-Mail from A to B on 2018-01-25` or
    
    + `USB-Stick given personally from C to D on 2018-01-26`

* Restriction of usage, e.g.

    + `only for project x` or 
    
    + `only within KWB` or
    
    + `must not be published!` or 
    
    + `should be published!`!

* Description of content and format

    + Where measurements were taken?
    
    + What methods were used (to take samples, to analyse parameters in the
    laboratory)?
    
    + What devices where used?
    
    + What do the columns of the table (in the database, XLS/CSV file) mean?
    
    + In what units are the values given?

##### Metadata about Processed Data

What are the most important information about the data that we produce?

* Who created the file? If the file was created by a script, what script created
the file and who ran the script?

* When was the file created?

* What was the input data (e.g. [raw data](#raw-data) or preprocessed data)?

* Which methods were applied to generate the output from the input?

* What was the environment, what were boundary conditions, e.g.

    + versions of software,
    
    + versions of R packages?

##### Metadata about Programming Scripts

* What does the script do?

* Who wrote the script?

* How to use the script? Give a short tutorial.

Regarding R programming, we should consider providing scripts in the form of 
R packages. The R packaging system defines a framework of how to answer all of 
the above questions. See how we did this (not yet always with with a tutorial) 
with [our packages on GitHub](https://github.com/kwb-r).

#### Where to Store Metadata? {#metadata-where}

The two main options of storing metadata are:

1. together with the data or near to the data i.e. in the same folder in which 
the data file resides,

2. in a central file or database.

Unless we have a professional solution (i.e. software on metadata management) 
we should prefer the first approach which is simpler and more flexible than the
second one.

#### In What Format to Store Metadata? {#metadata-format}

keep metadata in plain text file “readme.txt”

#### Metadata Management Tools

Tools for metadata tracking and data standards are:

* metadata editor, e.g. online editor of GFZ Potsdam

#### Metadata Standards {#metadata-standards}

We want to use a metadata standard. 

Examples for metadata standards are (in brackets are listed the institutions who 
publish their data by using this standard):

- [DataCite metadata scheme](https://schema.datacite.org/)

    + [Leibniz-Zentrum für Agrarlandschaftsforschung e. V. (ZALF)](http://www.zalf.de)
    
    + [Deutsches GeoForschungsZentrum Potsdam (GFZ)](http://dataservices.gfz-potsdam.de/portal/) (+ ISO + DIF + [Dublin Core](http://dublincore.org/))

- [ISO 19115-2](https://www.iso.org/standard/39229.html)

    + [Bundesanstalt für Gewässerkunde (BfG)](https://www.re3data.org/repository/r3d100011664)
    
    + [Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research 
    (AWI)](https://www.awi.de/en.html)


```{block2, type = 'rmdnote'} 

Best-practices roadmap:

1. Check meta data standards, e. g. [DataCite](https://schema.datacite.org/) (see 
also: ZALF, GFZ Potsdam)  
  
2. Define minimum metadata requirements at KWB for raw and processed data.  
projects. 

The 'best-practices for metadata' will be developed for the [case studies](#case-studies) 
which are assessed within FAKIN project.

We propose to define some special files that contain metadata related 
to files and folders. To indicate that these files have a special meaning, the
file names are all uppercase.
```

<!-- ***copied from `10_old_german_chapters.Rmd` ***: -->

<!-- Beispiel: -->

<!-- Wenn wir Zeitreihen von den Beliner Wasserbetrieben bekommen, dann haben diese -->
<!-- entweder eine Spalte mit Zeitstempeln oder zwei Spalten mit Zeitstempeln, wobei -->
<!-- die erste den Anfang und die zweite das Ende des Zeitraums enthält, auf den -->
<!-- sich die Messwerte in der entsprechenden Zeile beziehen.  -->

<!-- Wenn nur eine Spalte Zeitstempel enthält, dann ist nicht klar, ob der  -->
<!-- Zeitstempel den Anfang oder das Ende (oder gar einen anderen Zeitpunkt  -->
<!-- innerhalb) des Zeitraums angibt.  -->

<!-- Bei einer Zeitreihe mit fünfminütigen Messwerten, z.B. -->

<!-- ``` -->
<!-- Zeit                Wert -->
<!-- 2018-06-05 16:20:00    0 -->
<!-- 2018-06-05 16:25:00    1 -->
<!-- 2018-06-05 16:30:00    2 -->
<!-- 2018-06-05 16:35:00    3 -->
<!-- 2018-06-05 16:40:00    4 -->
<!-- ``` -->

<!-- ist nicht klar, ob sich der Wert 1 auf den Zeitraum `16:20 - 16:25` oder auf -->
<!-- den Zeitraum `16:25 - 16:30` bezieht. -->

<!-- Dies ist ein Beispiel für eine sehr konkrete Metadatenanforderung. An dieser -->
<!-- Stelle gehen wir meistens von Annahmen aus oder hat jemand von Euch schon mal -->
<!-- eine Aussage darüber von einem BWB-Mitarbeiter erhalten? -->

<!-- Die Kenntnis über den Bezugspunkt des Zeitstempels ist zum Beispiel wichtig beim -->

<!-- * [Erzeugen von Regen-Inputdateien für die Software InfoWorks](#input-infoworks-regen) -->

<!-- In der obigen Beispielzeitreihe ist auch nicht klar, auf welche Zeitzone sich -->
<!-- die Zeitstempel beziehen. Die Zeitzone bzw. die Angabe des UTC-Offsets ist eine -->
<!-- wichtige Metainformation. Am besten wäre es, wenn alle Zeitstempel diese  -->
<!-- Information enthielten, z.B. -->

<!-- ``` -->
<!-- 2018-06-05 16:20:00+02 -->
<!-- 2018-06-05 16:25:00+02 -->
<!-- ``` -->

<!-- Dann bräuchte man diese Information nicht extra zu führen.  -->

<!-- Metadaten werden oft erst bei Bedarf erhoben, nämlich genau dann, wenn man sich -->
<!-- z.B. die obigen Fragen nach Zeitstempelbezug und Zeitzone stellt. Dann wird -->
<!-- nachgefragt und im besten Fall wird eine Antwort darauf gegeben, z.B. in Form -->
<!-- einer E-Mail. Die Metadaten sind dann in der E-Mail enthalten.  -->

<!-- Fragen: -->

<!-- - Wo und unter welchem Namen legen wir diese E-Mail ab? -->

<!-- Beispiel für Metadaten aus meiner persönlichen Logdatei: -->

<!-- > Regendaten gelesen; ca. 10 Impulse gegen 14:00; Dannecker geschrubbt,  -->
<!-- > neuer Akku: Batterie defect, alte Batterie drin gelassen,  -->
<!-- > Daten auslesen nicht möglich; H=55cm -->

<!-- Das müssen wir irgendwie besser hinkriegen, aber wie? -->

<!-- Die grundlegenden Fragen sind: -->

<!-- - Wer ist für die Ablage von Metadaten verantwortlich? -->
<!-- - Wo werden die Metadaten abgelegt? Direkt bei den Daten oder in einer  -->
<!-- übergeordneten Datei/Datenbank? -->
<!-- - In welchem Format werden die Metadaten abgelegt? Einfaches Textformat vs.  -->
<!-- XML-Format, das sich wohl einfach nur mit Hilfe eines Programms editieren lässt. -->


#### File PROJECTS.txt {#file-projects}

This file contains the [project acronyms](#project-acronyms) as we want to use 
them e.g. as top-level folder names in our 
[project folder structure](#project-folder-structure).
The projects are grouped by department.

Possible content of `PROJECTS.txt`:

```
# Department SUW (Surface Water)
dswt: DSWT
flusshygiene: Flusshygiene
kuras: KURAS
mia-cso: MIACSO
monitor: MONITOR
ogre: OGRE
reliable-sewer: RELIABLE_SEWER
sema: SEMA
sema-berlin: SEMA Berlin
sema-berlin-2: SEMA Berlin 2
spree-2011: SPREE2011
spree-2011-2: SPREE2011 "reloaded"

# Department GRW (Groundwater)
optiwells: OPTIWELLS
optiwells-2: OPTIWELLS 2
wellma: WELLMA

# Department WWT (Wastewater Treatment)
...
```

In the file `PROJECTS.txt` the project acronyms appear in alphabetical
order. They map the acronym to a project name or a project title and the year
of the start of the project. 

**Question:**
Do we already have a place where "official" metadata about projects are stored? 
If yes, the acronym could be included there. But then, everybody should know 
about it!

#### File ORGANISATIONS.txt {#file-organisations}

Possible content of `ORGANISATIONS.txt`

```
bwb: Berliner Wasserbetriebe
kwb: Kompetenzzentrum Wasser Berlin
uba: Umweltbundesamt
```


### Raw Data {#raw-data}

Especially in environmental sciences, [raw data](#raw-data) often cannot be
reproduced (e.g. rainfall, river discharge measurements) and are therefore of 
high value. Thus the following rules apply in case of raw data: 

-	can be renamed (in case this is documented in a [metadata](#metadata) file)

-	the content must not be changed

-	will be stored as read-only in an secure area (i.e. one folder contains all 
[raw data](#raw-data))

***added from: 04_rawdata.Rmd***

As [raw data](#raw-data) we define data that we receive from a device or from a project
partner. 

Most of our research results are based on data. We acknowledge the importance
of [raw data](#raw-data) by

* storing then in a special place where it is specially secured

* describing them with [metadata](#metadata)

Rawdata are stored in the [rawdata folder structure](#rawdata-folder-structure)


### Data Workflow

For each project separation of:

* [raw data](#raw-data) (i.e. `\\server\\rawdata`)

* data processing (i.e. `\\server\\processing`)

* results (i.e. `\\server\\projekte$`)


Raw data are highly valuable because they if necessary cannot or only with high 
costs be reproduced. Thus raw data will be compiled on the highest level (i.e. 
`\\server\\rawdata`) for each `project` and `origin` (e.g. KWB, BWB) as shown 
below:

**Raw data folder structure:**

```
TestProjekt
  BWB
    Regen
      METADATEN
      regen.xls
    Labor
      METADATEN
      labor.xls

  KWB
    Durchfluss
      METADATEN
      q01.csv
      q02.csv
      q03.csv
```

The data processing is a "playground", where different approaches or scenarios
can be tested and where possibly different versions for a specific approach
or scenario are available. The files will be stored here according to the 
corresponding `project` and `topic` and the data processing step, respectively.


**Data processing folder structure:**

```
TestProjekt
  01_Bereinigung
    METADATEN
    regen_roh.csv
    regen.csv
    qualitaet.csv      
    durchfluss.csv
  02_Modellierung
    sommer
    winter
    VERSIONEN
      v0.1
      v1.0
        sommer
        winter
  Software
```

In the results folder only the "reporting relevant" results should be saved. 
Relevant results files (e.g. plots) should be added according to  `project` and 
`project structure` (i.e. per `working package`) in form of links from the 
`data processing` folder structure (see above).


**Results folder structure:**

```
TestProjekt
  Data-Work Packages
    WP1_Monitoring
    WP2_Modellierung
      sommer.lnk
      winter.lnk
```

### Folder Structures {#folder-structures}

Restrictions/Conventions:

* Each top-level folder should represent a project, i.e. should be defined in
the top level file [`PROJECTS.txt`](#file-projects). 
* Each possible owner should be defined in the top level file
[`ORGANISATIONS.txt`](#file-organisations).
* The naming convention for the organisations is the same as for projects.
s)


#### Project Folder Structure {#project-folder-structure}

We said that we want to concentrate on the folder structures within the project 
folders. Nevertheless, we would like to give a recommendation on how the project
folders could be organised within its top level folder. In this structure, there
are no subfolders for the different departments any more. 

```
//server/projects$
- PROJECTS.txt
- project-1/
- project-2/
- project-3/
```

In the `projects$` folder

- each subfolder name should appear in the file [`PROJECTS.txt`](#file-projects)
- there should not be any folder on the top level that does not represent a 
project. 
- there should be no other files on the top level as the files that are
described in this documentation.
- there are no subfolders representing departments any more. The mapping of
projects to departments is done in the file [`PROJECTS.txt`](#file-projects)

#### Rawdata Folder Structure {#rawdata-folder-structure}

We will create a network folder `//server/rawdata$` in which all files
have set the read-only property. We suggest to store raw data by project first
and by the organisation that owns (i.e. generated, provided) the data second. 
This could look like this:

```
//server/rawdata$
- ORGANISATIONS.txt
- PROJECTS.lnk [Symbolic Link to PROJECTS.txt in //server/projects$]
- flusshygiene
  - bwb
  - kwb
  - uba
  - ...
- ogre
  - kwb
  - bwb
  - uba
  - ...
- ...
```


### Versioning

Versioning or version control is the way by which different versions and drafts 
of a document (or file or record or dataset or software code) are managed. 
Versioning involves the process of naming and distinguishing between a series 
of draft documents that leads to a final or approved version in the end. 
Versioning allows you to disclose an audit trail for the revision and update of 
drafts and final versions.


#### Manual 

We propose the following workflow:

- It is only allowed to modify the current file (e.g. `filename.pptx`), which 
contains no version name as postfix

- A version is created by copying the current file. This copy gets a not already 
defined version name as file name ending (e.g. `filename_v0.1.pptx`) 

- The versioned file is moved to a folder `VERSIONS" and set as read-only.

- In the folder `VERSIONS` is a file `VERSIONS.txt`, which contrains addtional 
information on the available version within that folder

**Drawbacks:**

* possibly more time demanding, 

* needs time getting used to it and

* requires high level of discipline


**Advantages:**

* Simple and safe method, which requires not version control software

* Cleaner workspace as old versions are stored in a separate folder

* Sorting by name equals the chronology

**Example:**

```
BestPractices_Workshop.ppt
VERSIONS/
  + VERSIONS.txt
  + BestPractices_Workshop_v0.1.ppt
  + BestPractices_Workshop_v0.2.ppt
  + BestPractices_Workshop_v1.0.ppt
```

Content of file `VERSIONS.txt`:

```
BestPractices_Workshop.ppt
- v0.1: first draft version, written by Michael Rustler
- v0.2: after additions by Hauke Sonnenberg
- v1.0: first final version, after review by Pascale Rouault
```

#### Automatically

The versioning is done automatically in case a version control software, 
like [Git](https://en.wikipedia.org/wiki/Git) or [Subversion](https://en.wikipedia.org/wiki/Apache_Subversion) 
are used. 

At KWB we currently use the following version control software: 

- [Subversion](https://subversion.apache.org): for internally storing programm 
code (e.g. R-scripts/packages) we have an Subversion server, which is accessible 
from the KWB intranet. However, this requires: 

    + the installation of the client software [TortoiseSVN](https://tortoisesvn.net/index.de.html) 
    and a
    
    + valid user account (for accessing the server) which is currently provided by the 
    IT department on request


- [Git](https://git-scm.com/): for publishing programm code external on our KWB organisation group on [Github](https://github.com/KWB-R). Currently all repositories are public (i.e. 
are visible for everyone), but also use of private repositories is possible for 
free as KWB is recognised as non-for-profit company by Github, offering [additional
benefits for free](https://help.github.com/articles/discounted-organization-accounts/#discounts-for-nonprofits-and-libraries)

```{block2 rmdcaution}
Use of version control software is required in case of programming (e.g. in R, 
Python, and so on) and can be useful in case of tracking changes in small text 
files (e.g. configuration files that run a specific R script with different 
parameters for scenario analysis). 
```

**Drawbacks:**

* Special software ([TortoiseSVN](https://tortoisesvn.net/index.de.html)), login 
data for each user on KWB-Server and some basic training are required

* In case of collaborate coding: sticking to 'best-practices' for using version 
control is mandatory, e.g.: 
 
    + timely check in of code changes to the central server, 
    
    + Speaking to each other: so that not two people work at the same time at the 
    same program code in one script as this leads to conflicts that need to be 
    resolved manually, which can be quite time demanding. You are much better off 
    if you avoid this in the upfront by talking to each other

**Advantages:**

* Only one filename per script (file history and code changes are managed either 
internally on a KWB server in case of using TortoiseSVN or externally for code 
hosted on Github) 

* Old versions of scripts can be restored easily 

* Additional comments during `commit` (i.e. at the time of transfering the code 
from the local computer to the central version control system about `why` code 
changes were made and build-in diff-tools for tracking changes improve the 
reproducibility

```{block2,  type='rmdwarning'}
Attention: version control software is not designed for versioning of raw data 
and thus should not be used for it. General thoughts on the topic of 'data 
versioning' are available here: [https://github.com/leeper/data-versioning](https://github.com/leeper/data-versioning) 
```

```{block2, type = 'rmdnote'}

A presentation with different tools for version control is available here: 
[https://www.fosteropenscience.eu/node/597](https://www.fosteropenscience.eu/node/597)

```

### Organising E-Mails

> "Most people now routinely send and receive lots of messages every day and as a 
Yesult, their inbox can get very quickly overloaded with hundreds of personal and
work-related email. Setting aside some time to organise your emails will ensure 
information can be found quickly and easily, and is stored securely.
Why should I organise my email?
Apart from the obvious frustration and time wasted looking for that email you 
remember sending to someone last month, email is increasingly used to store 
important documents and data, often with information related to the attachments 
within the email itself." 
>
> --- [University of Cambridge (2018)](https://www.data.cam.ac.uk/data-management-guide/organising-your-data#Refernces)

**How can I ensure my emails remain organised?**

Here are some general tips to ensure your email remains organised in the long 
term [University of Cambridge, 2018](https://www.data.cam.ac.uk/data-management-guide/organising-your-data#Refernces):

- Delete emails you do not need. Remove any trivial or old messages from your 
inbox and sent items on a regular (ideally daily) basis.

- 	Use folders to store messages. Establish a structured file directory by 
subject, activity or project.

-	Separate personal emails. Set up a separate folder for these. Ideally, you 
should not receive any personal emails to your work email account.

-	Limit the use of attachments. Use alternative and more secure methods to 
exchange data where possible (see ‘data sharing’ for options). If attachments 
are used, exercise version control and save important attachments to other 
places, such as a network drive.


### Managing References 

For managing reference there are plenty of tools available. A detailed overview 
is provided by `r citep(manual["Fenner_2014"])` in the Chapter [Reference Management](http://book.openingscience.org.s3-website-eu-west-1.amazonaws.com/tools/reference_management.html) 
At KWB we use Endnote, for which an internal guideline document ([KWB-EndNote-Guideline-v02.pdf](file://Y:/R&D Templates/Charts Guidelines Checklists/KWB-EndNote-Guideline-v02.pdf), `r add_text_links()`) was developed.
<!-- add_text_links() only adds more details in case of html output as 
defined in "R/add_text.R" -->

### Data Preservation
Data must be retained to support your research findings

Standards: ?5 years?

