## Folder Structures {#folder-structures}

### Project Folder Structure {#project-folder-structure}

We said that we want to concentrate on the folder structures within the project 
folders. Nevertheless, we would like to give a recommendation on how the project
folders could be organised within its top level folder. In this structure, there
are no subfolders for the different departments any more. 

```
//server/projects$
- PROJECTS.txt
- project-1/
- project-2/
- project-3/
```

In the `projects$` folder

- each subfolder name should appear in the file [`PROJECTS.txt`](#file-projects)
- there should not be any folder on the top level that does not represent a 
project. 
- there should be no other files on the top level as the files that are
described in this documentation.
- there are no subfolders representing departments any more. The mapping of
projects to departments is done in the file [`PROJECTS.txt`](#file-projects)

### Rawdata Folder Structure {#rawdata-folder-structure}

We will create a network folder `//server/rawdata$` in which all files
have set the read-only property. We suggest to store raw data by project first
and by the organisation that owns (i.e. generated, provided) the data second. 
This could look like this:

```
//server/rawdata$
- ORGANISATIONS.txt
- PROJECTS.lnk [Symbolic Link to PROJECTS.txt in //server/projects$]
- flusshygiene
  - bwb
  - kwb
  - uba
  - ...
- ogre
  - kwb
  - bwb
  - uba
  - ...
- ...
```

Restrictions/Conventions:

* Each top-level folder should represent a project, i.e. should be defined in
the top level file [`PROJECTS.txt`](#file-projects). 
* Each possible owner should be defined in the top level file
[`ORGANISATIONS.txt`](#file-organisations).
* The naming convention for the organisations is the same as for projects.
