# Projects {#projects}

## Spree2011 (2007)

Used data by source (data formats in parentheses)

* KWB:
    + water level and discharge at one monitoring site (Text/CSV)
    + rain (Text/CSV)
* BWB:
    + pumping rates in the pumping stations (Excel)
    + water levels in the pumping stations (Excel)
    + rain at some gauges near the monitoring site (Excel)
    
Tasks and methods by topic

* Dry-weather and wet-weather calibration of a sewer network model (Infoworks)

    + [InfoWorks: Creating rain input files](#input-infoworks-regen)
    + [InfoWorks: Creating RTC input files](#input-infoworks-rtc)

Questions that arose:

* Where to store presentations (trainee vs. employee)?
* Where to store the raw data (personal drive of the trainee)?
* How does Infoworks interpret timestamps, how do BWB provide timestamps? 
-> [metadata](#metadata)

## MIACSO (2009) {#miacso}

Monitoring

* sites: one site in the sewer (monitoring container), more sites in the river
* variables: water quantity and quality
* devices: online sensors

Modelling

* Sewerage: Infoworks
* River hydraulics: Hydrax
* River quality: QSim

Data storage

* High amount of data -> extra server: `moby`
* We put some effort in planning good folder structures for the data.
Nevertheless the structure at the end of the project is not as clean as it was
planned.
* Data that we received from project partners was stored in `Daten/EXTERN`.
* Raw data was stored in a folder `Daten/RAW` which was write-protected and
required a special user-account for storing new data.

```
Daten/
  ACCESS/ # MS Access databases, containing raw data
  EXTERN/ # External data (by organisation)
  META/   # MS Access databases, containing metadata 
          # (about calibration, maintenane, sites, variables)
  RAW/    # Text files containing raw data, from KWB-own devices only, by site
```

Metadata

* many devices in the container -> meta data about device cleaning and
maintenance important -> tool: `META_Maintenance.mdb`

Methods and Tools

* We imported most of the data from text files into MS Access databases in
-> tool: `MiaCsoRawImport.mdb`
* We calibrated the sensors offline by using SQL queries to provide calibrated
data from raw data -> tool: `MiaCsoMetaCalibControl.mdb`
* We used SQL queries to perform data processing 
-> tool: `MiaCsoStatAnalysis.mdb`
* Data validation (outlier detection) was done in a two step procedure:
    1. Automatic preselection using MS Access tool `MiaCsoStatAnalysis.mdb`
    2. Manual selection using self-developed graphical tool in Origin 

Developed Tools:

* MS Access Applications
    + `MetaMaint.mdb`: Monitoring Metadata Management
    + `MiaCsoRawImport.mdb`: Text File Import to MS Access
    + `MiaCsoStatAnalysis.mdb` (project deliverable): Definition and automatic 
execution of sequences of SQL queries
* Origin extension to interactively select and store outliers graphically
* R packages
    + `kwb.mia.evalCritO2` (project deliverable): graphical evaluation of 
critical oxygen conditions in the river
    + `kwb.mia.iw`: Calculation of file sizes of InfoWorks result csv-files
        exported from InfoWorks.
    + `kwb.miacso`: functions used in MIA-CSO, for example for plotting data 
availabilities.

## KURAS {#kuras}

Developed Tools:

* Frontend for KURAS Database of Rainwater Management Measures: 
`KURAS_DB_Acc2003_hs.mdb`
* R package `kwb.kuras`: Interface to KURAS database

## OGRE {#ogre}

* Decision to use [CUAHSI Community Observations Data Model (ODM)](https://www.cuahsi.org/uploads/pages/img/ODM1.1DesignSpecifications_.pdf)
* R script to import lab data from Excel to MS Access database implementing ODM

Developed Tools:

* R packages
    + `kwb.ogre`
    + `kwb.ogre.model`
    + `kwb.odm`
    + `kwb.odmx`

## Flusshygiene {#flusshygiene}

* Adaptation of free online monitoring data visualisation [HydroServerLite](https://github.com/KWB-R/HydroServerLite)
* Reusage of lab data import script developed in [OGRE](#ogre)

## DEMOWARE {#demoware}

Entstandene R Pakete: 

- Grundwassermodellierung

    + [kwb.hantush](https://github.com/kwb-r/kwb.hantush)
    
    + kwb.vs2dh
    
    + kwb.demoware

- Quantitatives mikrobiologisches Risikomanagement

    + [kwb.qmra](https://github.com/kwb-r/kwb.qrma): wird im Rahmen von AQUANES(#aquanes) weiter genutzt

## OPTIWELLS {#optiwells}

Created R packages: 

* [kwb.wtaq](https://github.com/kwb-r/kwb.wtaq): Groundwater Modelling
* kwb.epanet: (Pressure)Pipe Network Simulation (EPANET)

## RWE {#rwe}

(Semi)automatisierte Erstellung eines komplexen MODFLOW Modells (mehrere Layer, mehrere hunderte Entnahmebrunnen mit zeitlich variierender Entnahmemenge sowie Hinzufügen/Entfernen von Brunnen innerhalb des Simulationszeitraums) in Phyton mittels [flopy](http://modflowpy.github.io/flopydoc/) sowie Entwicklung der Modellszenarien auf Github (siehe hier: [Maxflow](https://github.com/chmenz/Maxflow)).

Input Christian !?!

## AQUANES {#aquanes}

Created R package: 

* [aquanes.report](https://github.com/kwb-r/aquanes.report): data import, 
temporal aggregation, interactive visualisation of operational data of
pilot facilities and joining with lab data

Sites (among others):

* [Berlin-Tiefwerder](http://aquanes-h2020.eu/Default.aspx?t=1576)
* [Berlin-Schönerlinde](http://aquanes-h2020.eu/Default.aspx?t=1666)
* [Basel Lange-Erlen](http://aquanes-h2020.eu/Default.aspx?t=1663)
* [Haridwar](http://aquanes-h2020.eu/Default.aspx?t=1668)

Challenges: 

* zeitlich hoch aufgelöste Betriebsdaten (~ 10 Mio. Datenpunkte pro Monat) 
erforderten massive Performance Optimierung um die Visualisierung der Rohdaten
im Tool über den Testbetriebszeitraum (18 Monate) auf Rechnern mit limitierten 
RAM Ressourcen (~ 8 GB) zu ermöglichen.
    
* Nutzung: wird von den Projektpartnern zum strukturierten Datenimport genutzt 
um dann darauf ggf. eigene weitere Analysen darauf aufzusetzen. Für die beiden 
Berliner Standorte wird zudem die Visualiserung der Betriebsdaten routinenäßig 
genutzt, um vom Regelbetrieb abweichende Zustände besser indentifizieren zu können.
