---
title: "FAKIN Documentation Index"
author: "Hauke Sonnenberg"
date: "2018-06-04"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: kwb-r/fakin.doc
url: 'https\://kwb-r.github.io/fakin.doc'
description: "FAKIN Projektdokumentation"
---

# Einführung

Hier wollen wir die Ergebnisse unseres Forschungsprojekts FAKIN 
(Forschungsdatenmanagement an kleinen Instituten) veröffentlichen.

## Fallbeispiele

Da wir viele, zum Teil ganz unterschiedliche Projekte bearbeiten, sind auch 
unterschiedliche Bereiche des Forschungsdatenmanagements betroffen.

Wir wollen hier zunächst versuchen, Fallbeispiele herauszuarbeiten, in die sich
die verschiedenen Projekte einordnen lassen. Für jedes Fallbeispiel wollen wir
dann Gemeinsamkeiten in Bezug auf Anforderungen und Problemstellungen
herausarbeiten und für diese dann Lösungen entwickeln. Diese Lösungen sollen 
dann in zukünftigen Projekten, die sich den jeweiligen Fallbeispielen 
zuordnen lassen, angewendet werden.

## Projektbausteine

Wir können "Projektbausteine" definieren, die in verschiedenen Projekten
vorkommen. Diese werden im Folgenden einzeln betrachtet.

### Monitoring

In vielen Projekten führen wir eigene Messungen durch. Dazu verwenden wir 
eigene Messgeräte.

Problemstellungen:

* verschiedene Geräte verschiedener Hersteller -> verschiedene, meist nicht
  standardisierte Dateiformate
* Zeitstempel der Messung
    + Stellt das Gerät auf Sommerzeit um? 
    -> [Problembereich Zeitstempel](#zeitstempel)
    + Geht die interne Uhr immer richtig? Wie gewährleiste ich das?

Beispielprojekte:

- MIACSO
- KURAS
- Flusshygiene

### Kanalnetzmodellierung

Beispielprojekte:

- MIACSO
- KURAS
- Flusshygiene

### Datenimport {#datenimport}

### Fallbeispiel: LCA (Life Cycle Assessment = Lebenszyklusbewertung)

## Problembereiche

### Zeitstempel {#zeitstempel}

**Frage:**

Wie stellen wir die Messgeräte ein? Sollen sie die Uhr automatisch umstellen 
oder nicht?

**Diskussion:**

Aus Sicht der Datenverarbeitung bereitet uns die Umstellung von Winterzeit 
(= Normalzeit) auf Sommerzeit und von Sommerzeit auf Winterzeit immer wieder
Schwierigkeiten. Warum? 

**Umstellung von Winterzeit auf Sommerzeit**

Die Uhr wird um eine Stunde von 02:00 CET (*Central European Time*) auf 
03:00 CEST (*Central European Summer Time*) **vorgestellt**. 
Merke: Die Stühle eines Cafés werden **vor** den Laden gestellt.

In einer Zeitreihe ergibt sich daraus am Tag der Zeitumstellung (z.B. am 
25.03.2018) eine Lücke in den Zeitstempeln:

```
2018-03-25 01:45:00 CET
2018-03-25 01:50:00 CET
2018-03-25 01:55:00 CET
2018-03-25 03:00:00 CEST
2018-03-25 03:05:00 CEST
2018-03-25 03:10:00 CEST
```

**Umstellung von Sommerzeit auf Winterzeit** 

Die Uhr wird um 03:00 CEST wieder um eine Stunde auf die Normalzeit 02:00 CET **zurückgestellt**. 
Merke: Die Stühle werden wieder in den Laden **zurück** gestellt.

In einer Zeitreihe ergeben sich daraus am Tag der Zeitumstellung 
(z.B. am 28.10.2018) Duplikate in den Zeitstempeln:

```
2018-10-28 02:15:00 CEST
2018-10-28 02:30:00 CEST
2018-10-28 02:45:00 CEST
2018-10-28 02:00:00 CET
2018-10-28 02:15:00 CET
2018-10-28 02:30:00 CET 
```

**TODO:** Ggf. weitere Beschreibungen in R-Workshop, den ich mal gegeben habe...

**Vorschlag:**

- Nach Möglichkeit die Messgeräte so einstellen, dass der ausgegebene 
  Zeitstempel den UTC-Offset enthält. Am besten wäre ein Zeitstempel in einem
  Format, das die Differenz gegenüber *Greenich Mean Time (GMT)* bzw. 
  *Coordinated Universal Time (UTC)* enthält, wie wir es ggf. aus unseren 
  E-Mail-Programmen oder Terminkalendern kennen: `2018-06-01 23:18 GMT+02:00`.
- Manchmal gibt es auch die Möglichkeit, dass zusätzlich zum lokalen Zeitstempel
  der UTC-Offset (+01 im Winter und +02 im Sommer) als extra Spalte ausgegeben 
  wird. Von dieser Möglichkeit sollte dann Gebrauch gemacht werden.
- Ansonsten die Geräte so einstellen, dass sie die Zeitumstellung nicht 
  mitmachen (also immer die Normalzeit, also Winterzeit aufzeichnen). Dann sind 
  die Zeitstempel eindeutig. Aufzupassen ist dann allerdings bei der 
  Verarbeitung und Interpretation der Daten, dazu mehr unter 
  [Datenimport](#datenimport)

**Werkzeuge:**

KWB-eigenes R-Paket [`kwb.datetime`](https://kwb-r.github.io/kwb.datetime/dev). 
Dieses enthält unter anderem die Funktionen

- [`date_range_CEST()`](https://kwb-r.github.io/kwb.datetime/dev/reference/date_range_CEST.html)
  zur Ermittlung der Tage, an denen die Zeitumstellung stattfindet.
- **TODO:** Wichtigste Funktionen (z.B. zur Ermittlung der vollständigen 
  Zeitstempel inklusive UTC-Offset aus fortlaufenden lokalen Zeitstempeln)
  dokumentieren und hier referenzieren. Oder welche Pakete sollten wir benutzen?
  Was bietet z.B. `lubridate`? Es scheint mir allerdings, dass unsere 
  Problematik im WWW etwas unterbeleuchtet ist. 
  